# Generated by Django 3.1.7 on 2021-03-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsliderdata',
            name='image',
            field=models.ImageField(help_text='Image Size should be 484x441', upload_to='uploads'),
        ),
    ]
