# Generated by Django 3.1.7 on 2021-03-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicsite', '0002_auto_20210308_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsliderdata',
            name='price_badge_image',
            field=models.ImageField(blank=True, help_text='Image Size should be 172x172', null=True, upload_to='uploads'),
        ),
    ]
