# Generated by Django 3.1.7 on 2021-03-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicsite', '0003_mainsliderdata_price_badge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyterm',
            name='billing_system',
            field=models.TextField(blank=True, null=True),
        ),
    ]
