# Generated by Django 3.1.7 on 2021-02-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210224_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='currency',
        ),
        migrations.DeleteModel(
            name='MainSliderData',
        ),
        migrations.DeleteModel(
            name='PolicyTerm',
        ),
        migrations.DeleteModel(
            name='PublicMessage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='GeneralInfo',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
