# Generated by Django 3.1.7 on 2021-03-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210224_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='recommend_image',
            field=models.ImageField(blank=True, help_text='Image Size should be 268x134', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Image Size should be 266x381', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Image Size should be 268x249', null=True, upload_to='uploads'),
        ),
    ]
